In [1]:
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 30 20:58:00 2023

@author: Gibson Nkhata
"""
import random
import numpy as np
from math import pi,tan,sqrt

## Problem 1. Class and Inheritance

### Geometry class

In [2]:
class Geometry: 
    geometry_count = 0
    def __init__(self, name = "Shape", points = None): 
        self.name = name  
        self.points = points 
        Geometry.geometry_count += 1
      
    def __del__(self): 
        Geometry.geometry_count -= 1 

    def calculate_area(self): 
        pass 
        
    def get_name(self): 
        return self.name 
    
    def distance(self, index1, index2):
        x1 = self.points[index1][0]
        y1 = self.points[index1][1]
        x2 = self.points[index2][0]
        y2 = self.points[index2][1]
        return sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)
        
    @classmethod 
    def count_number_of_geometry(cls): 
        print("Number of geometry instances: %d" % cls.geometry_count)


### Triangle class

In [3]:
class Triangle(Geometry): 
    def __init__(self, a, b,c ):
        super(Triangle, self).__init__("Triangle", [a, b, c])

    def calculate_area(self):
        side1 = self.distance(0,1)
        side2 = self.distance(0,2)
        side3 = self.distance(1,2)
        sp    = (side1+side2+side3)/2
        hf  = sp*((sp-side1)*(sp-side2)*(sp-side3))
        return sqrt(hf) 
    
triangle = Triangle((0, 1), (1, 0), (0, 0))
print("Area of %s: %0.4f" % (triangle.name, triangle.calculate_area()))
Geometry.count_number_of_geometry()


Area of Triangle: 0.5000
Number of geometry instances: 1


### Rectangle class

In [4]:
class Rectangle(Geometry):
    def __init__(self, a,b):
        x1, y1 = a
        x2, y2 = b
        c = (x1, y2)
        d = (x2, y1)
        super(Rectangle, self).__init__("Rectangle", [a,b,c,d])
        
        
    def calculate_area(self):
        width = side1 = self.distance(0,2)
        height = self.distance(1,3)       
        return width*height
    
rectangle = Rectangle((0, 0), (2, 2))
print("Area of %s: %0.4f" % (rectangle.name, rectangle.calculate_area()))
Geometry.count_number_of_geometry()

Area of Rectangle: 4.0000
Number of geometry instances: 2


### Square class

In [5]:
class Square(Rectangle):
    def __init__(self, a, length):
        x, y = a
        b = (x + length, y - length)
        super(Square, self).__init__( a,b)
        self.name = "Square"
    
    def calculate_area(self):
        width = side1 = self.distance(0,2)
        return width**2   
    
square = Square((0, 0), 2)
print("Area of %s: %0.4f" % (square.name, square.calculate_area()))
Geometry.count_number_of_geometry()

Area of Square: 4.0000
Number of geometry instances: 3


### Circle class

In [6]:
class Circle(Geometry): 
    def __init__(self, o, rad):
        super(Circle, self).__init__("Circle", [o])
        self.rad = rad
    
    def calculate_area(self):
        area = pi*self.rad**2
        return area
        
circle = Circle((0, 0), 3)
print("Area of %s: %0.4f" % (circle.name, circle.calculate_area()))
Geometry.count_number_of_geometry()

Area of Circle: 28.2743
Number of geometry instances: 4


### Polygon class

In [7]:
class Polygon(Geometry): 
    def __init__(self, points):
        super(Polygon, self).__init__("Polygon", points)
    
    def calculate_area(self):
        sides = len(self.points)
        S = 0
        for i in range(2, sides):
            ab, ac, bc = self.distance(0, i - 1), self.distance(0, i), self.distance(i, i - 1)
            p = (ab + ac + bc) / 2
            S += np.sqrt(p * (p - ab) * (p - ac) * (p - bc))
        return S
    
polygon = Polygon([(0, 0), (0, 1), (1, 1), (1, 0)])
print("Area of %s: %0.4f" % (polygon.name, polygon.calculate_area()))
Geometry.count_number_of_geometry()

Area of Polygon: 1.0000
Number of geometry instances: 5


## Problem 2

### a. Matrix multiplication

In [8]:
def matrix_multiplication(A, B):
    result = np.zeros((len(A), len(B[1])))
    for x in range(len(A)):
        for y in range(len(B[1])):
            for z in range(len(B)):
                result[x][y] += A[x][z] * B[z][y]
    return result
                
A = np.random.randn(4, 5) 
B = np.random.randn(5, 6)

assert (A.dot(B) == matrix_multiplication(A, B)).any(), "Your implementation is wrong!"
print("Your implementation is correct!")

Your implementation is correct!


### b. Powers of a Matrix 

### Recursive functiion

In [9]:
def pow(A, n):
    if (n == 0):
        return np.eye(A.shape[0])
    else:
        B = pow(A, n / 2)
        B = A.dot(A)
        if (n % 2) == 0:
            return B
        else:
            return B @ A
        


In [10]:
for test in range(10):
    n = random.randint(2, 5)
    A = np.random.randn(n, n)
    #print(A)
    print("A^{} = {}".format(n, pow(A, n)))
    print()

A^4 = [[-1.17350692  0.45143022  0.74229987  0.17109624]
 [-0.05252752  6.9996382  -0.33859418  0.59055102]
 [-0.8094624  -1.02237213  0.19973491 -0.97441233]
 [-1.1464152  -3.80531789  0.53588654 -0.22841917]]

A^2 = [[-0.45845668 -0.37505932]
 [ 0.31360391 -0.36924819]]

A^3 = [[ 0.92566371  4.98121973 -0.83600909]
 [-0.0290138   3.63879379 -1.14979763]
 [ 3.51969537 -1.52769068  4.71770782]]

A^2 = [[ 3.07750317 -0.98524332]
 [-1.26258219  0.40525133]]

A^2 = [[3.51522784 1.92258297]
 [0.74436053 0.40729717]]

A^4 = [[-2.01271896 -2.57933477 -1.50696935 -0.93749445]
 [ 3.81790753  2.67668255  1.20645755  5.62891736]
 [ 3.30384451  2.21961215  2.52103839  2.27127978]
 [-0.0563938   0.35674482  0.12557357  1.31301787]]

A^2 = [[ 0.51976678 -0.09592732]
 [ 1.204584    0.42004557]]

A^2 = [[-1.2356804   0.28787465]
 [-0.18770636 -0.96880855]]

A^2 = [[-0.31817285 -0.33842573]
 [ 0.92700756 -1.2022352 ]]

A^4 = [[ 1.47460232  4.08003523 -3.85692079 -1.51684715]
 [-4.0844271  -1.19355137 

### Iterative functon

In [11]:
def pow(A, n):
    result = np.eye(A.shape[0])
    while (n > 0):
        if (n % 2) == 1:
            result = result @ A
        A = A.dot(A)
        n = n // 2
    return result

In [12]:
for test in range(10):
    n = random.randint(2, 5)
    A = np.random.randn(n, n)
    print("A^{} = {}".format(n, pow(A, n)))
    print()

A^4 = [[ 16.87376115  -6.01498967  -3.83023048   2.37870668]
 [-27.40110866  24.78930426  -9.96559567   0.91195899]
 [-22.99859237  -0.26805561  14.34787011  -5.93536276]
 [  6.3958998   20.97414376 -26.5056456    8.29295479]]

A^4 = [[ 24.91689484 -21.54844946 -13.94659204   1.81063464]
 [ -3.06255645  34.58585648  -1.07938462  22.38468746]
 [ -0.30963082  -5.50233394   5.20137283  -2.40667421]
 [ 17.51770204   2.39235513  -5.93858979  18.24749138]]

A^5 = [[ -8.76688032 -40.1534169   16.53227682  39.324501    22.25583164]
 [  2.10568324 -24.62520409  20.17494201  24.57797303   4.30995299]
 [-52.37714368 -34.80805478 -36.82841105  -4.68096836   6.14093654]
 [-25.21806398 -15.4548217  -19.12049949 -14.18097756 -17.46132231]
 [-46.3744619   -3.09079627 -55.2594112  -19.11022094   6.70324386]]

A^3 = [[-0.55150116 -0.17583504  0.70884816]
 [ 2.5319539  -0.45559392  0.8656012 ]
 [ 0.21555522  0.497502   -0.3530091 ]]

A^2 = [[1.65806631 2.7303037 ]
 [0.45767244 2.41057965]]

A^4 = [[-17.7

## c. Fibonacci number

In [13]:
def get_A():
    return np.array([[1., 1.], [1., 0.]])

def fibo(n):
    A = get_A()
    F1 = np.array([[1.], [1.]])
    FN = pow(A, n - 1) @ F1
    return int(FN[0][0])

In [14]:
a, b = 1, 1
for i in range(2, 10):
    c = a + b
    assert (fibo(i) == c), "You implementation is incorrect"
    print("[Test Case %d]. Your implementation is correct!. fibo(%d) = %d" % (i - 2, i, fibo(i)))
    a = b
    b = c

[Test Case 0]. Your implementation is correct!. fibo(2) = 2
[Test Case 1]. Your implementation is correct!. fibo(3) = 3
[Test Case 2]. Your implementation is correct!. fibo(4) = 5
[Test Case 3]. Your implementation is correct!. fibo(5) = 8
[Test Case 4]. Your implementation is correct!. fibo(6) = 13
[Test Case 5]. Your implementation is correct!. fibo(7) = 21
[Test Case 6]. Your implementation is correct!. fibo(8) = 34
[Test Case 7]. Your implementation is correct!. fibo(9) = 55


## d. Recursive Function

In [15]:
def f(n, k):
    if (n < k):
        return 1
    else:
        ret = 0
        for i in range(1, k + 1):
            ret += f(n - i, k)
    return ret

In [16]:
for n in range(5, 11):
    for k in range(2, 5):
        print("f(%d, %d) = %d" % (n, k, f(n,k)))

f(5, 2) = 8
f(5, 3) = 9
f(5, 4) = 7
f(6, 2) = 13
f(6, 3) = 17
f(6, 4) = 13
f(7, 2) = 21
f(7, 3) = 31
f(7, 4) = 25
f(8, 2) = 34
f(8, 3) = 57
f(8, 4) = 49
f(9, 2) = 55
f(9, 3) = 105
f(9, 4) = 94
f(10, 2) = 89
f(10, 3) = 193
f(10, 4) = 181


## 3a DFS

In [17]:
def recursiveDFS(x, y, A, visited, path):
    M = A.shape[0]
    N = A.shape[1]
    visited[x][y] = 1
    if (x == M - 1 and y == N - 1):
        print("(0, 0)", end = "")
        for (u, v) in path:
            print(" -> (%d, %d)" % (u, v), end ="")
        print()
        exit(0)
    for dx, dy in [(-1, 0), (0, -1), (1, 0), (0, 1)]:
        u = x + dx
        v = y + dy
        if (0 <= u) and (u < M) and (0 <= v) and (v < N) and (A[u][v] != 0) and visited[u][v] == 0:
            path.append((u, v))
            recursiveDFS(u, v, A, visited, path)
            path.pop()

def DFS(A):
    recursiveDFS(0, 0, A, np.zeros_like(A), [])

In [18]:
As = np.load("test.npy", allow_pickle=True)
for test in range(len(As)):
    A = As[test]
    print("Test Case %d" % test)
    print(A) 
    DFS(A) 
    print()

Test Case 0
[[1 1 1 1 0 1 1 0]
 [1 1 1 1 0 1 0 1]
 [1 1 0 1 1 1 1 1]
 [1 1 1 1 0 1 0 1]
 [1 1 1 0 1 1 0 1]
 [1 1 1 0 1 1 1 1]
 [1 1 1 1 0 0 1 0]
 [1 1 0 1 1 1 1 1]
 [0 0 0 0 1 1 1 1]]
(0, 0) -> (1, 0) -> (2, 0) -> (3, 0) -> (4, 0) -> (5, 0) -> (6, 0) -> (7, 0) -> (7, 1) -> (6, 1) -> (5, 1) -> (4, 1) -> (3, 1) -> (2, 1) -> (1, 1) -> (0, 1) -> (0, 2) -> (1, 2) -> (1, 3) -> (2, 3) -> (3, 3) -> (3, 2) -> (4, 2) -> (5, 2) -> (6, 2) -> (6, 3) -> (7, 3) -> (7, 4) -> (8, 4) -> (8, 5) -> (7, 5) -> (7, 6) -> (8, 6) -> (8, 7)

Test Case 1
[[1 1 1 1 1 0 1 1]
 [0 1 1 1 1 1 1 1]
 [1 1 0 1 0 1 0 0]
 [1 1 0 0 1 1 0 0]
 [1 1 1 1 1 0 1 0]
 [1 0 1 1 1 1 1 1]
 [0 1 0 0 1 1 0 1]
 [1 0 1 1 1 1 1 1]]
(0, 0) -> (0, 1) -> (1, 1) -> (2, 1) -> (2, 0) -> (3, 0) -> (4, 0) -> (4, 1) -> (4, 2) -> (5, 2) -> (5, 3) -> (4, 3) -> (4, 4) -> (5, 4) -> (6, 4) -> (7, 4) -> (7, 5) -> (6, 5) -> (5, 5) -> (5, 6) -> (5, 7) -> (6, 7) -> (7, 7)

Test Case 2
[[1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 1 1 0 0 1 0 

## 3b. BFS

In [2]:
def BFS(A):
    M = A.shape[0]
    N = A.shape[1]
    visited = np.zeros_like(A)
    prevx = np.ones_like(A) * -1
    prevy = np.ones_like(A) * -1
    queue = [(0, 0)]
    visited[0][0] = 1
    while (len(queue) > 0):
        x, y = queue.pop(0)
        for dx, dy in [(-1, 0), (0, -1), (1, 0), (0, 1)]:
            u = x + dx
            v = y + dy
            if (0 <= u) and (u < M) and (0 <= v) and (v < N) and (A[u][v] != 0) and visited[u][v] == 0:
                prevx[u][v] = x
                prevy[u][v] = y
                queue.append((u, v))
                visited[u][v] = 1
    path = []
    x, y = M - 1, N - 1
    while (x != 0 or y != 0):
        u, v = prevx[x][y], prevy[x][y]
        path.append((u, v))
        x, y = u, v
    for u, v in path[::-1]:
        print("(%d, %d) -> " % (u, v), end="")
    print("(%d, %d)" % (M - 1, N - 1))

In [3]:
As = np.load("test.npy", allow_pickle=True)
for test in range(len(As)):
    A = As[test]
    print("Test Case %d" % test)
    print(A) 
    BFS(A)  
    print()

Test Case 0
[[1 1 1 1 0 1 1 0]
 [1 1 1 1 0 1 0 1]
 [1 1 0 1 1 1 1 1]
 [1 1 1 1 0 1 0 1]
 [1 1 1 0 1 1 0 1]
 [1 1 1 0 1 1 1 1]
 [1 1 1 1 0 0 1 0]
 [1 1 0 1 1 1 1 1]
 [0 0 0 0 1 1 1 1]]
(0, 0) -> (1, 0) -> (2, 0) -> (3, 0) -> (4, 0) -> (5, 0) -> (6, 0) -> (6, 1) -> (6, 2) -> (6, 3) -> (7, 3) -> (7, 4) -> (8, 4) -> (8, 5) -> (8, 6) -> (8, 7)

Test Case 1
[[1 1 1 1 1 0 1 1]
 [0 1 1 1 1 1 1 1]
 [1 1 0 1 0 1 0 0]
 [1 1 0 0 1 1 0 0]
 [1 1 1 1 1 0 1 0]
 [1 0 1 1 1 1 1 1]
 [0 1 0 0 1 1 0 1]
 [1 0 1 1 1 1 1 1]]
(0, 0) -> (0, 1) -> (1, 1) -> (2, 1) -> (3, 1) -> (4, 1) -> (4, 2) -> (5, 2) -> (5, 3) -> (5, 4) -> (6, 4) -> (7, 4) -> (7, 5) -> (7, 6) -> (7, 7)

Test Case 2
[[1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 1 1 0 0 1 0 0]
 [0 0 1 1 1 1 1 0]
 [0 0 1 0 1 1 1 1]
 [1 1 1 0 1 1 0 1]]
(0, 0) -> (1, 0) -> (1, 1) -> (1, 2) -> (2, 2) -> (3, 2) -> (4, 2) -> (4, 3) -> (4, 4) -> (5, 4) -> (5, 5) -> (5, 6) -> (5, 7) -> (6, 7)

Test Case 3
[[1 1 1 1 1 0 0 1 1]
 [0 1 1 0 0 0 1 1 1]
 [1 1 1

## 3c. Advanced question

In [4]:
import heapq
def findMinimum(A):
    M = A.shape[0]
    N = A.shape[1]
    visited = np.zeros_like(A)
    prevx = np.ones_like(A) * -1
    prevy = np.ones_like(A) * -1
    cost = np.ones_like(A) * 100000
    queue = []
    heapq.heappush(queue, (A[0][0], (0, 0)))
    cost[0][0] = A[0][0]
    while (len(queue) > 0):
        c, (x, y) = heapq.heappop(queue)
        visited[x][y] = 1
        if (cost[x][y] != c):
            continue
        for dx, dy in [(-1, 0), (0, -1), (1, 0), (0, 1)]:
            u = x + dx
            v = y + dy
            if (0 <= u) and (u < M) and (0 <= v) and (v < N) and (A[u][v] != 0) and visited[u][v] == 0 and cost[x][y] + A[u][v] < cost[u][v]:
                prevx[u][v] = x
                prevy[u][v] = y
                cost[u][v] = cost[x][y] + A[u][v]
                heapq.heappush(queue, (cost[u][v], (u, v)))
    path = []
    x, y = M - 1, N - 1
    while (x != 0 or y != 0):
        u, v = prevx[x][y], prevy[x][y]
        path.append((u, v))
        x, y = u, v
    print("Cost: %d" % cost[M-1][N-1])
    for u, v in path[::-1]:
        print("(%d, %d) -> " % (u, v), end="")
    print("(%d, %d)" % (M - 1, N - 1))

In [5]:
As = np.load("test.npy", allow_pickle=True)
for test in range(len(As)):
    A = As[test]
    print("Test Case %d" % test)
    print(A) 
    findMinimum(A) 
    print()

Test Case 0
[[1 1 1 1 0 1 1 0]
 [1 1 1 1 0 1 0 1]
 [1 1 0 1 1 1 1 1]
 [1 1 1 1 0 1 0 1]
 [1 1 1 0 1 1 0 1]
 [1 1 1 0 1 1 1 1]
 [1 1 1 1 0 0 1 0]
 [1 1 0 1 1 1 1 1]
 [0 0 0 0 1 1 1 1]]
Cost: 16
(0, 0) -> (0, 1) -> (0, 2) -> (0, 3) -> (1, 3) -> (2, 3) -> (2, 4) -> (2, 5) -> (3, 5) -> (4, 5) -> (5, 5) -> (5, 6) -> (6, 6) -> (7, 6) -> (7, 7) -> (8, 7)

Test Case 1
[[1 1 1 1 1 0 1 1]
 [0 1 1 1 1 1 1 1]
 [1 1 0 1 0 1 0 0]
 [1 1 0 0 1 1 0 0]
 [1 1 1 1 1 0 1 0]
 [1 0 1 1 1 1 1 1]
 [0 1 0 0 1 1 0 1]
 [1 0 1 1 1 1 1 1]]
Cost: 15
(0, 0) -> (0, 1) -> (1, 1) -> (2, 1) -> (3, 1) -> (4, 1) -> (4, 2) -> (4, 3) -> (4, 4) -> (5, 4) -> (5, 5) -> (5, 6) -> (5, 7) -> (6, 7) -> (7, 7)

Test Case 2
[[1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 1 1 0 0 1 0 0]
 [0 0 1 1 1 1 1 0]
 [0 0 1 0 1 1 1 1]
 [1 1 1 0 1 1 0 1]]
Cost: 14
(0, 0) -> (0, 1) -> (0, 2) -> (0, 3) -> (0, 4) -> (0, 5) -> (1, 5) -> (2, 5) -> (3, 5) -> (4, 5) -> (4, 6) -> (5, 6) -> (5, 7) -> (6, 7)

Test Case 3
[[1 1 1 1 1 0 0 1 1]
 